

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1006521620Jhoer
      POSTGRES_DB: citas_medicas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postman:
    image: postman/newman
    command: ["run", "https://www.postman.com/collections/your_collection_url"]
    depends_on:
      - backend

volumes:
  pgdata:
